name: "Filter paths"
description: "Filters changed files according to docker image builds and releases"
inputs:
  changedFiles: # id of input
    description: "Changed files"
    required: true
    default: ""
  depth: # id of input
    description: "Depth of needed directories"
    required: false
    default: -1
outputs:
  filteredPaths: # id of output
    description: "Filtered paths"
runs:
  using: "node16"
  main: "index.js"
